# Generated by Django 5.2.6 on 2025-09-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('user_location', models.CharField(max_length=50)),
                ('internship_location', models.CharField(max_length=50)),
                ('graduation_year', models.IntegerField()),
                ('gpa', models.FloatField()),
                ('experience', models.FloatField()),
                ('user_skills', models.TextField()),
                ('required_skills', models.TextField()),
                ('company', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('is_selected', models.BooleanField(default=False)),
            ],
        ),
    ]
