INSERT INTO internshiprequirements(id, age, description, gender, max_experience, min_experience, mode, percentage, specialization, stream, internship_id, minimum_qualification_rank) VALUES
(1,18,'Basic understanding of C and microcontrollers; willing to work in lab.','Any',2,0,'Onsite',65,'Embedded Systems','Electronics',1,3),
(2,20,'Proficient in HTML, CSS, JS; knowledge of React preferred.','Any',3,0,'Onsite',70,'Frontend Development','Computer Science',2,3),
(3,19,'Familiarity with production lines and QC basics preferred.','Any',4,0,'Onsite',60,'Quality Assurance','Mechanical',3,2),
(4,21,'Laboratory handling skills, data entry accuracy and documentation.','Any',3,0,'Onsite',65,'Clinical Research','Pharmacy/Biotech',4,3),
(5,22,'Comfortable with Excel and financial modeling basics.','Any',5,0,'Onsite',65,'Finance','Commerce/Finance',5,3),
(6,23,'Strong visual design sense and Figma/Sketch experience.','Any',3,0,'Remote/Onsite',70,'UI/UX','Design',6,3),
(7,20,'Basic inventory knowledge and barcode systems.','Any',4,0,'Onsite',60,'Logistics','Commerce',7,2),
(8,21,'Food safety basics and sensory analysis interest.','Any',2,0,'Onsite',60,'Food Technology','Food Science',8,3),
(9,22,'Willingness to travel to rural areas and manage events.','Any',2,0,'Field',60,'CSR','Social Work',9,3),
(10,18,'Good communication and cash handling awareness.','Any',1,0,'Onsite',55,'Retail Operations','Commerce',10,1),
(11,22,'Node.js/Express and relational DB familiarity required.','Any',3,0,'Onsite',65,'Backend Development','Computer Science',11,3),
(12,21,'SEO basics and content calendar experience preferred.','Any',2,0,'Remote/Onsite',65,'Digital Marketing','Marketing',12,3),
(13,20,'Community health interest; ability to maintain accurate records.','Any',2,0,'Field',60,'Public Health','Public Health/Nursing',13,3),
(14,22,'Basic agronomy or farm systems knowledge useful.','Any',3,0,'Field',60,'Agronomy','Agriculture',14,3),
(15,21,'Understanding of plant operations and safety protocols.','Any',5,1,'Onsite',60,'Manufacturing','Mechanical/Production',15,3),
(16,22,'Molecular biology lab experience preferred; sterile technique.','Any',4,0,'Onsite',70,'Pharma R&D','Biotechnology/Pharmacy',16,3),
(17,23,'Experience in data labeling and Python ML libraries helpful.','Any',3,0,'Onsite/Remote',70,'Machine Learning','Computer Science',17,3),
(18,20,'Friendly communicator and problem solver for customer escalations.','Any',2,0,'Remote/Onsite',55,'Customer Support','Any',18,2),
(19,21,'Experience with packaging design or sustainability research.','Any',3,0,'Onsite',65,'Packaging Design','Design',19,3),
(20,19,'Comfortable with field surveys and sales outreach.','Any',2,0,'Field',55,'Sales','Commerce',20,2),
(21,22,'Interest in renewable energy with basic electrical knowledge.','Any',3,0,'Onsite',60,'Renewable Energy','Electrical/Mechanical',21,3),
(22,21,'Coordination skills and familiarity with last-mile logistics.','Any',3,0,'Onsite',55,'Logistics','Any',22,2),
(23,23,'Clinical data handling and familiarity with spreadsheets.','Any',3,0,'Onsite',65,'Clinical Data','Life Sciences',23,3),
(24,22,'PM mindset and ability to own small product features.','Any',3,0,'Onsite',65,'Product Management','Any',24,3),
(25,20,'Knowledge of automotive testing methods a plus.','Any',2,0,'Onsite',60,'Automotive Testing','Automobile Engineering',25,3),
(26,21,'Familiarity with seller onboarding processes and KYC basics.','Any',2,0,'Onsite',60,'E-commerce Operations','Any',26,2),
(27,22,'Clinical exposure and patient privacy training required.','Any',3,0,'Onsite',65,'Clinical','Nursing/MBBS',27,3),
(28,22,'Sensor prototyping experience and basic coding valued.','Any',2,0,'Onsite',65,'Agritech','Electronics/Agriculture',28,3),
(29,23,'Materials testing fundamentals and lab safety required.','Any',3,0,'Onsite',65,'Materials Science','Metallurgy/Materials',29,3),
(30,24,'Legal basics and good drafting skills; research exposure.','Any',2,0,'Onsite',65,'Legal','Law',30,3),
(31,21,'Strong Excel and SQL basics for dashboarding.','Any',3,0,'Onsite/Remote',65,'Business Analytics','Any',31,3),
(32,22,'Field coordination and community mobilization skills.','Any',3,0,'Field',60,'Rural Development','Social Work/Development',32,3),
(33,22,'Flutter or mobile development fundamentals required.','Any',3,0,'Onsite/Remote',65,'Mobile Development','Computer Science',33,3),
(34,21,'Merchandising sense and SKU tracking knowledge.','Any',2,0,'Onsite',55,'Merchandising','Commerce',34,2),
(35,23,'Chemical process understanding and lab safety awareness.','Any',3,0,'Onsite',65,'Process Engineering','Chemical Engineering',35,3),
(36,21,'Clinical lab basics and sample handling required.','Any',2,0,'Onsite',65,'Quality Control','Pharmacy/Science',36,3),
(37,20,'Content creation and multimedia skills preferred.','Any',2,0,'Remote/Onsite',60,'Content Creation','Media/Communication',37,2),
(38,22,'Strong statistics and R/Python skills for survey analysis.','Any',3,0,'Onsite',70,'Economics Research','Economics/Statistics',38,3),
(39,21,'Fabrication or welding basics useful; safety compliance required.','Any',3,0,'Onsite',60,'Welding Engineering','Mechanical',39,3),
(40,20,'Clinical diagnostics knowledge and lab etiquette needed.','Any',2,0,'Onsite',60,'Diagnostics','Life Sciences',40,2),
(41,22,'Interviewing and qualitative research experience valuable.','Any',2,0,'Field',65,'Field Research','Sociology/Anthropology',41,3),
(42,21,'Physical prototyping skills and CAD experience preferred.','Any',2,0,'Onsite',65,'Industrial Design','Design',42,3),
(43,23,'Credit risk modeling basics and Excel competency required.','Any',3,1,'Onsite',65,'Risk Analytics','Finance/Statistics',43,3),
(44,22,'Polymer lab handling and testing knowledge desired.','Any',3,0,'Onsite',65,'Polymer Chemistry','Chemistry/Material Science',44,3),
(45,21,'Campus coordination and communication skills.','Any',2,0,'Onsite',60,'HR Operations','Any',45,2),
(46,22,'Soil testing basics and field sampling training.','Any',2,0,'Field',60,'Soil Science','Agriculture',46,3),
(47,23,'Supplier contracting and negotiation basics helpful.','Any',3,0,'Onsite',65,'Procurement','Commerce',47,3),
(48,22,'Pharmacovigilance interest and basic regulatory knowledge.','Any',3,0,'Onsite',65,'Pharmacovigilance','Pharmacy/Pharmacology',48,3),
(49,21,'Instructional design mindset and LMS familiarity.','Any',2,0,'Remote',65,'Instructional Design','Education/E-learning',49,3),
(50,22,'Wind farm operations basics and safety compliance required.','Any',3,0,'Onsite',60,'Wind Energy','Mechanical/Electrical',50,3),
(51,21,'Usability research and test moderation skills preferred.','Any',2,0,'Onsite',65,'User Research','Design/Psychology',51,3),
(52,20,'Mobile testing methodology and device familiarity.','Any',2,0,'Onsite',60,'Mobile QA','IT',52,2),
(53,22,'Sustainable packaging research experience desirable.','Any',3,0,'Onsite',65,'Sustainable Packaging','Design/Material Science',53,3),
(54,21,'Farmer engagement experience and community outreach skills.','Any',2,0,'Field',60,'Extension','Agriculture/Social Work',54,2),
(55,22,'Predictive maintenance basics and sensor data understanding.','Any',3,0,'Onsite',65,'Maintenance Engineering','Mechanical',55,3),
(56,22,'Cell culture lab experience and safety procedures required.','Any',3,0,'Onsite',70,'Molecular Biology','Biotech/Biology',56,3),
(57,23,'Vendor coordination and procurement analytics preferred.','Any',3,0,'Remote/Onsite',65,'Supply Chain','Commerce',57,3),
(58,22,'Pharma QC techniques and documentation experience desired.','Any',3,0,'Onsite',70,'Quality Control','Pharmacy/Chemistry',58,3),
(59,21,'Storytelling and short-form content experience helpful.','Any',1,0,'Remote/Onsite',60,'Content Creation','Media',59,2),
(60,24,'Strong microeconomics and survey analysis ability useful.','Any',2,0,'Onsite',65,'Economics Research','Economics',60,4),
(61,22,'Welding and materials understanding required for shop floor support.','Any',3,0,'Onsite',60,'Welding','Mechanical',61,3),
(62,21,'Diagnostics QA procedures and lab hygiene critical.','Any',2,0,'Onsite',60,'Diagnostics','Life Sciences',62,2),
(63,23,'Qualitative research skills and note-taking proficiency required.','Any',2,0,'Field',65,'Field Research','Social Sciences',63,3),
(64,22,'3D CAD and prototyping experience expected.','Any',3,0,'Onsite',65,'Industrial Design','Design/Mechanical',64,3),
(65,24,'NLP familiarity and Python modeling experience preferred.','Any',2,0,'Onsite/Remote',70,'NLP','Computer Science',65,3),
(66,22,'SLA monitoring experience and vendor handling skills.','Any',3,0,'Onsite',60,'Operations','Any',66,2),
(67,21,'Selenium or automated testing basics useful.','Any',2,0,'Onsite',65,'QA Automation','Computer Science',67,3),
(68,24,'Financial modeling basics and investor pitch familiarity.','Any',2,0,'Onsite',65,'IR Research','Finance',68,3),
(69,23,'Sustainability assessments and familiarity with GHG calculators helpful.','Any',2,0,'Onsite',65,'Sustainability','Environmental Science',69,3),
(70,22,'Fixture design and mechanical drawing skills useful.','Any',3,0,'Onsite',65,'Mechanical Design','Mechanical',70,3),
(71,23,'Clinical trial knowledge and consent procedure familiarity.','Any',2,0,'Onsite',70,'Clinical Trials','Life Sciences',71,3),
(72,24,'Public policy research experience and report writing.','Any',2,0,'Onsite',65,'Public Policy','Political Science',72,4),
(73,22,'Embedded and cloud connectivity experience helpful for IoT.','Any',3,0,'Onsite',65,'IoT','Electronics/CS',73,3),
(74,21,'Creative thinking and campaign ideation experience preferred.','Any',2,0,'Onsite',60,'Brand Management','Marketing',74,3),
(75,22,'ETL basics and SQL proficiency required for BI tasks.','Any',3,0,'Onsite',70,'BI','Computer Science/IT',75,3),
(76,20,'Customer handling and store-level UX observation capability.','Any',2,0,'Onsite',55,'Customer Experience','Commerce',76,2),
(77,23,'Power systems fundamentals and SCADA exposure desired.','Any',4,0,'Onsite',65,'Power Systems','Electrical',77,3),
(78,22,'GIS knowledge and mapping skills helpful for urban planning.','Any',3,0,'Onsite',65,'Urban Planning','Civil/Planning',78,3),
(79,21,'Hospitality rotation flexibility and guest-facing skills needed.','Any',2,0,'Onsite',55,'F&B','Hospitality',79,2),
(80,22,'Data pipeline and Spark/SQL experience valuable.','Any',3,0,'Onsite',70,'Data Engineering','Computer Science',80,3),
(81,23,'Maintenance and instrumentation understanding required.','Any',3,0,'Onsite',65,'Maintenance Engineering','Mechanical',81,3),
(82,22,'PCR, aseptic technique and lab documentation experience required.','Any',3,0,'Onsite',70,'Molecular Biology','Biotech',82,3),
(83,21,'Supplier analytics and inventory reconciliation skills beneficial.','Any',2,0,'Onsite',65,'Supply Chain','Commerce',83,3),
(84,23,'Stability study knowledge and documentation best practices.','Any',3,0,'Onsite',70,'Quality Control','Pharmacy',84,3),
(85,20,'Short-form video shoot/edit experience preferred.','Any',1,0,'Remote/Onsite',55,'Content Creation','Media',85,2),
(86,24,'Survey sampling and econometric analysis skills preferred.','Any',2,0,'Onsite',70,'Economics Research','Economics/Statistics',86,4),
(87,22,'Fabrication permits and safety experience required for welding shop.','Any',3,0,'Onsite',60,'Welding','Mechanical',87,3),
(88,21,'Diagnostics test SOP understanding and QC processes required.','Any',2,0,'Onsite',60,'Diagnostics','Life Sciences',88,2),
(89,23,'Interview scheduling and transcription skills useful.','Any',2,0,'Field',65,'Field Research','Social Sciences',89,3),
(90,22,'CAD and 3D printing skills desirable.','Any',3,0,'Onsite',65,'Industrial Design','Design',90,3),
(91,23,'NLP libraries and preprocessing experience needed.','Any',3,0,'Onsite/Remote',70,'NLP','CS',91,3),
(92,21,'SLA and reporting basics for operations support.','Any',2,0,'Onsite',55,'Operations','Any',92,2),
(93,22,'Test automation and scripting ability preferred.','Any',2,0,'Onsite',65,'QA Automation','CS/IT',93,3),
(94,24,'Financial research and presentation skills required.','Any',2,0,'Onsite',65,'IR Research','Finance',94,3),
(95,23,'GHG accounting basics and sustainability reporting interest.','Any',2,0,'Onsite',65,'Sustainability','Environmental Science',95,3),
(96,22,'3D CAD/ Solidworks and prototyping familiarity expected.','Any',3,0,'Onsite',65,'Mechanical Design','Mechanical',96,3),
(97,23,'Clinical trial coordination basics and GCP exposure helpful.','Any',2,0,'Onsite',70,'Clinical Trials','Life Sciences',97,3),
(98,24,'Policy analysis and qualitative coding experience valuable.','Any',2,0,'Remote/Onsite',65,'Public Policy','Social Sciences',98,4),
(99,22,'Connectivity stacks and embedded C familiarity desirable.','Any',3,0,'Onsite',65,'IoT','Electronics/CS',99,3),
(100,21,'Design thinking and rapid prototyping skills required.','Any',2,0,'Onsite',65,'Brand Management','Marketing/Design',100,3);
