INSERT INTO app_user(id, age, district, email, experience, gender, name, percentage, specialization, state, stream, highest_qualification_rank) VALUES
(1,18,'Kolkata','avinash.poddar@example.com',0,'Male','Avinash Poddar',87.4,'Physics-Chemistry-Math','West Bengal','High School Science',2),
(2,19,'Jaipur','neha.sharma@example.com',0,'Female','Neha Sharma',89.2,'Biology','Rajasthan','High School Science',2),
(3,22,'Bengaluru','pranav.kumar@example.com',2,'Male','Pranav Kumar',74.5,'Computer Science','Karnataka','B.Tech',3),
(4,24,'Hyderabad','swarna.mehta@example.com',3.5,'Female','Swarna Mehta',78.6,'Data Science','Telangana','M.Tech',4),
(5,26,'Thiruvananthapuram','adi.nair@example.com',4,'Male','Adithya Nair',81.3,'Mechanical Engineering','Kerala','B.Tech',3),
(6,28,'Ahmedabad','meera.patel@example.com',5.2,'Female','Meera Patel',85,'Business Administration','Gujarat','MBA',4),
(7,30,'Lucknow','ravi.singh@example.com',7,'Male','Ravi Singh',69.8,'Electrical Engineering','Uttar Pradesh','B.Tech',3),
(8,32,'New Delhi','isha.jain@example.com',8,'Female','Isha Jain',88.1,'Law','Delhi','LLM',4),
(9,29,'Chennai','karthik.r@example.com',6.5,'Male','Karthik R',77,'Civil Engineering','Tamil Nadu','B.Tech',3),
(10,21,'Gurgaon','ananya.gupta@example.com',1,'Female','Ananya Gupta',91.2,'Computer Science','Haryana','B.Tech',3),
(11,23,'Patna','sachin.yadav@example.com',1.5,'Male','Sachin Yadav',72.4,'Agriculture','Bihar','BSc Agriculture',3),
(12,20,'Mysore','kavya.rani@example.com',0.5,'Female','Kavya Rani',83,'Commerce','Karnataka','High School Commerce',2),
(13,27,'Indore','pooja.kumar@example.com',4,'Female','Pooja Kumar',80.5,'Human Resources','Madhya Pradesh','MBA HR',4),
(14,25,'Noida','aman.verma@example.com',3,'Male','Aman Verma',75.2,'Finance','Uttar Pradesh','B.Com',3),
(15,31,'Kochi','deepika.nair@example.com',9,'Female','Deepika Nair',92.4,'Biotechnology','Kerala','PhD Biotechnology',5),
(16,34,'Vellore','suresh.p@example.com',10.5,'Male','Suresh P',70.6,'Pharmacy','Tamil Nadu','B.Pharm',3),
(17,35,'Bengaluru','latha.m@example.com',12,'Female','Latha M',86.7,'Design','Karnataka','M.Des',4),
(18,22,'Pune','tarun.rathod@example.com',1,'Male','Tarun Rathod',79.1,'Electronics','Maharashtra','B.Tech',3),
(19,24,'Kolkata','ishita.bose@example.com',2,'Female','Ishita Bose',90,'Journalism','West Bengal','MA Journalism',4),
(20,23,'Bhopal','rahul.jain@example.com',1.8,'Male','Rahul Jain',76.3,'Chemical Engineering','Madhya Pradesh','B.Tech',3),
(21,28,'Kanpur','neelam.verma@example.com',4.5,'Female','Neelam Verma',84,'Clinical Psychology','Uttar Pradesh','M.Sc Psychology',4),
(22,19,'Shimla','manish.thakur@example.com',0,'Male','Manish Thakur',91.5,'NA','Himachal Pradesh','High School General',1),
(23,26,'Mangalore','shruti.shetty@example.com',3.8,'Female','Shruti Shetty',82.2,'Computer Applications','Karnataka','BCA',3),
(24,27,'Raipur','vikram.singh@example.com',5.5,'Male','Vikram Singh',73.9,'Mining Engineering','Chhattisgarh','B.Tech',3),
(25,29,'Vadodara','pallavi.patel@example.com',6,'Female','Pallavi Patel',88.3,'Pharmaceutical Management','Gujarat','MBA Pharma',4),
(26,33,'Kozhikode','rahul.suresh@example.com',11,'Male','Rahul Suresh',87,'Environmental Science','Kerala','MSc Environmental Science',4),
(27,21,'Visakhapatnam','sakshi.rao@example.com',0.6,'Female','Sakshi Rao',78.9,'Marine Biology','Andhra Pradesh','BSc Biology',3),
(28,22,'Surat','aditya.patel@example.com',1.2,'Male','Aditya Patel',80,'Textile Engineering','Gujarat','B.Tech',3),
(29,24,'Chandigarh','ritu.malhotra@example.com',2.5,'Female','Ritu Malhotra',89.7,'Public Policy','Punjab','MA Public Policy',4),
(30,30,'Nagpur','vikas.agarwal@example.com',7.4,'Male','Vikas Agarwal',71.1,'Automobile Engineering','Maharashtra','B.Tech',3),
(31,36,'Kolkata','anjali.das@example.com',12.5,'Female','Anjali Das',93.4,'Economics','West Bengal','PhD Economics',5),
(32,40,'Delhi','sanjay.gupta@example.com',15,'Male','Sanjay Gupta',85.5,'Operations Management','Delhi','MBA',4),
(33,45,'Ahmednagar','reena.k@example.com',20,'Female','Reena K',78.2,'Education','Maharashtra','B.Ed',3),
(34,27,'Rajkot','chirag.patel@example.com',4.2,'Male','Chirag Patel',77.8,'Civil Engineering','Gujarat','B.Tech',3),
(35,22,'Pune','shraddha.pawar@example.com',1,'Female','Shraddha Pawar',86,'Information Technology','Maharashtra','B.Sc IT',3),
(36,24,'Guwahati','aman.kapoor@example.com',3,'Male','Aman Kapoor',88.8,'Marketing','Assam','MBA Marketing',4),
(37,26,'Ernakulam','divya.nair@example.com',4.5,'Female','Divya Nair',79.5,'Hospitality','Kerala','BHM',3),
(38,23,'Kurnool','kumar.s@example.com',2,'Male','Kumar S',74.4,'IT & Networking','Andhra Pradesh','B.Tech',3),
(39,21,'Dharamsala','mansi.kumar@example.com',0.4,'Female','Mansi Kumar',82.1,'Commerce','Himachal Pradesh','High School Commerce',2),
(40,25,'Aurangabad','rahul.bendre@example.com',3.6,'Male','Rahul Bendre',76,'Biotech','Maharashtra','B.Sc Biotechnology',3),
(41,28,'Aligarh','nazima.khan@example.com',5,'Female','Nazima Khan',84.7,'Sociology','Uttar Pradesh','MA Sociology',4),
(42,22,'Jabalpur','yash.rao@example.com',1,'Male','Yash Rao',81.2,'Statistics','Madhya Pradesh','B.Sc Statistics',3),
(43,29,'Varanasi','pooja.singh@example.com',6.5,'Female','Pooja Singh',90.1,'Clinical Research','Uttar Pradesh','MSc Clinical Research',4),
(44,20,'Bikaner','tarini.jain@example.com',0.2,'Female','Tarini Jain',95,'NA','Rajasthan','High School General',1),
(45,18,'Kolkata','avinash.poddar@example.com',0,'Male','Avinash Poddar',87.4,'Physics-Chemistry-Math','West Bengal','High School Science',2),
(46,18,'Bangalore','neha.sharma@example.com',0,'Female','Neha Sharma',89.2,'Biology-Chemistry-Math','Karnataka','High School Science',2),
(47,22,'Chennai','pranav.kumar@example.com',1.5,'Male','Pranav Kumar',83.5,'Computer Science','Tamil Nadu','B.Tech CS',3),
(48,24,'Mumbai','swarna.iyer@example.com',2,'Female','Swarna Iyer',91,'Data Science','Maharashtra','M.Tech Data Science',4),
(49,21,'Pune','adithya.singh@example.com',1,'Male','Adithya Singh',78.5,'Mechanical Engineering','Maharashtra','B.Tech Mechanical',3),
(50,26,'Kochi','meera.nair@example.com',3,'Female','Meera Nair',88.7,'Business Administration','Kerala','MBA',4);
