INSERT INTO app_user (age, email, experience, gender, highestqualification, district, state, name, percentage, specialization, stream) VALUES
(18, 'avinash.poddar@example.com', 0.0, 'Male', '12', 'Kolkata', 'West Bengal', 'Avinash Poddar', 87.4, 'Physics-Chemistry-Math', 'High School Science'),
(19, 'neha.sharma@example.com', 0.0, 'Female', '12', 'Jaipur', 'Rajasthan', 'Neha Sharma', 89.2, 'Biology', 'High School Science'),
(22, 'pranav.kumar@example.com', 2.0, 'Male', 'UG', 'Bengaluru', 'Karnataka', 'Pranav Kumar', 74.5, 'Computer Science', 'B.Tech'),
(24, 'swarna.mehta@example.com', 3.5, 'Female', 'PG', 'Hyderabad', 'Telangana', 'Swarna Mehta', 78.6, 'Data Science', 'M.Tech'),
(26, 'adi.nair@example.com', 4.0, 'Male', 'UG', 'Thiruvananthapuram', 'Kerala', 'Adithya Nair', 81.3, 'Mechanical Engineering', 'B.Tech'),
(28, 'meera.patel@example.com', 5.2, 'Female', 'PG', 'Ahmedabad', 'Gujarat', 'Meera Patel', 85.0, 'Business Administration', 'MBA'),
(30, 'ravi.singh@example.com', 7.0, 'Male', 'UG', 'Lucknow', 'Uttar Pradesh', 'Ravi Singh', 69.8, 'Electrical Engineering', 'B.Tech'),
(32, 'isha.jain@example.com', 8.0, 'Female', 'PG', 'New Delhi', 'Delhi', 'Isha Jain', 88.1, 'Law', 'LLM'),
(29, 'karthik.r@example.com', 6.5, 'Male', 'UG', 'Chennai', 'Tamil Nadu', 'Karthik R', 77.0, 'Civil Engineering', 'B.Tech'),
(21, 'ananya.gupta@example.com', 1.0, 'Female', 'UG', 'Gurgaon', 'Haryana', 'Ananya Gupta', 91.2, 'Computer Science', 'B.Tech'),
(23, 'sachin.yadav@example.com', 1.5, 'Male', 'UG', 'Patna', 'Bihar', 'Sachin Yadav', 72.4, 'Agriculture', 'BSc Agriculture'),
(20, 'kavya.rani@example.com', 0.5, 'Female', '12', 'Mysore', 'Karnataka', 'Kavya Rani', 83.0, 'Commerce', 'High School Commerce'),
(27, 'pooja.kumar@example.com', 4.0, 'Female', 'PG', 'Indore', 'Madhya Pradesh', 'Pooja Kumar', 80.5, 'Human Resources', 'MBA HR'),
(25, 'aman.verma@example.com', 3.0, 'Male', 'UG', 'Noida', 'Uttar Pradesh', 'Aman Verma', 75.2, 'Finance', 'B.Com'),
(31, 'deepika.nair@example.com', 9.0, 'Female', 'PHD', 'Kochi', 'Kerala', 'Deepika Nair', 92.4, 'Biotechnology', 'PhD Biotechnology'),
(34, 'suresh.p@example.com', 10.5, 'Male', 'UG', 'Vellore', 'Tamil Nadu', 'Suresh P', 70.6, 'Pharmacy', 'B.Pharm'),
(35, 'latha.m@example.com', 12.0, 'Female', 'PG', 'Bengaluru', 'Karnataka', 'Latha M', 86.7, 'Design', 'M.Des'),
(22, 'tarun.rathod@example.com', 1.0, 'Male', 'UG', 'Pune', 'Maharashtra', 'Tarun Rathod', 79.1, 'Electronics', 'B.Tech'),
(24, 'ishita.bose@example.com', 2.0, 'Female', 'PG', 'Kolkata', 'West Bengal', 'Ishita Bose', 90.0, 'Journalism', 'MA Journalism'),
(23, 'rahul.jain@example.com', 1.8, 'Male', 'UG', 'Bhopal', 'Madhya Pradesh', 'Rahul Jain', 76.3, 'Chemical Engineering', 'B.Tech'),
(28, 'neelam.verma@example.com', 4.5, 'Female', 'PG', 'Kanpur', 'Uttar Pradesh', 'Neelam Verma', 84.0, 'Clinical Psychology', 'M.Sc Psychology'),
(19, 'manish.thakur@example.com', 0.0, 'Male', '10', 'Shimla', 'Himachal Pradesh', 'Manish Thakur', 91.5, 'NA', 'High School General'),
(26, 'shruti.shetty@example.com', 3.8, 'Female', 'UG', 'Mangalore', 'Karnataka', 'Shruti Shetty', 82.2, 'Computer Applications', 'BCA'),
(27, 'vikram.singh@example.com', 5.5, 'Male', 'UG', 'Raipur', 'Chhattisgarh', 'Vikram Singh', 73.9, 'Mining Engineering', 'B.Tech'),
(29, 'pallavi.patel@example.com', 6.0, 'Female', 'PG', 'Vadodara', 'Gujarat', 'Pallavi Patel', 88.3, 'Pharmaceutical Management', 'MBA Pharma'),
(33, 'rahul.suresh@example.com', 11.0, 'Male', 'PG', 'Kozhikode', 'Kerala', 'Rahul Suresh', 87.0, 'Environmental Science', 'MSc Environmental Science'),
(21, 'sakshi.rao@example.com', 0.6, 'Female', 'UG', 'Visakhapatnam', 'Andhra Pradesh', 'Sakshi Rao', 78.9, 'Marine Biology', 'BSc Biology'),
(22, 'aditya.patel@example.com', 1.2, 'Male', 'UG', 'Surat', 'Gujarat', 'Aditya Patel', 80.0, 'Textile Engineering', 'B.Tech'),
(24, 'ritu.malhotra@example.com', 2.5, 'Female', 'PG', 'Chandigarh', 'Punjab', 'Ritu Malhotra', 89.7, 'Public Policy', 'MA Public Policy'),
(30, 'vikas.agarwal@example.com', 7.4, 'Male', 'UG', 'Nagpur', 'Maharashtra', 'Vikas Agarwal', 71.1, 'Automobile Engineering', 'B.Tech'),
(36, 'anjali.das@example.com', 12.5, 'Female', 'PHD', 'Kolkata', 'West Bengal', 'Anjali Das', 93.4, 'Economics', 'PhD Economics'),
(40, 'sanjay.gupta@example.com', 15.0, 'Male', 'PG', 'Delhi', 'Delhi', 'Sanjay Gupta', 85.5, 'Operations Management', 'MBA'),
(45, 'reena.k@example.com', 20.0, 'Female', 'UG', 'Ahmednagar', 'Maharashtra', 'Reena K', 78.2, 'Education', 'B.Ed'),
(27, 'chirag.patel@example.com', 4.2, 'Male', 'UG', 'Rajkot', 'Gujarat', 'Chirag Patel', 77.8, 'Civil Engineering', 'B.Tech'),
(22, 'shraddha.pawar@example.com', 1.0, 'Female', 'UG', 'Pune', 'Maharashtra', 'Shraddha Pawar', 86.0, 'Information Technology', 'B.Sc IT'),
(24, 'aman.kapoor@example.com', 3.0, 'Male', 'PG', 'Guwahati', 'Assam', 'Aman Kapoor', 88.8, 'Marketing', 'MBA Marketing'),
(26, 'divya.nair@example.com', 4.5, 'Female', 'UG', 'Ernakulam', 'Kerala', 'Divya Nair', 79.5, 'Hospitality', 'BHM'),
(23, 'kumar.s@example.com', 2.0, 'Male', 'UG', 'Kurnool', 'Andhra Pradesh', 'Kumar S', 74.4, 'IT & Networking', 'B.Tech'),
(21, 'mansi.kumar@example.com', 0.4, 'Female', '12', 'Dharamsala', 'Himachal Pradesh', 'Mansi Kumar', 82.1, 'Commerce', 'High School Commerce'),
(25, 'rahul.bendre@example.com', 3.6, 'Male', 'UG', 'Aurangabad', 'Maharashtra', 'Rahul Bendre', 76.0, 'Biotech', 'B.Sc Biotechnology'),
(28, 'nazima.khan@example.com', 5.0, 'Female', 'PG', 'Aligarh', 'Uttar Pradesh', 'Nazima Khan', 84.7, 'Sociology', 'MA Sociology'),
(22, 'yash.rao@example.com', 1.0, 'Male', 'UG', 'Jabalpur', 'Madhya Pradesh', 'Yash Rao', 81.2, 'Statistics', 'B.Sc Statistics'),
(29, 'pooja.singh@example.com', 6.5, 'Female', 'PG', 'Varanasi', 'Uttar Pradesh', 'Pooja Singh', 90.1, 'Clinical Research', 'MSc Clinical Research'),
(20, 'tarini.jain@example.com', 0.2, 'Female', '10', 'Bikaner', 'Rajasthan', 'Tarini Jain', 95.0, 'NA', 'High School General'),
(18, 'avinash.poddar@example.com', 0.0, 'Male', '12', 'Kolkata', 'West Bengal', 'Avinash Poddar', 87.4, 'Physics-Chemistry-Math', 'High School Science'),
(18, 'neha.sharma@example.com', 0.0, 'Female', '12', 'Bangalore', 'Karnataka', 'Neha Sharma', 89.2, 'Biology-Chemistry-Math', 'High School Science'),
(22, 'pranav.kumar@example.com', 1.5, 'Male', 'UG', 'Chennai', 'Tamil Nadu', 'Pranav Kumar', 83.5, 'Computer Science', 'B.Tech CS'),
(24, 'swarna.iyer@example.com', 2.0, 'Female', 'PG', 'Mumbai', 'Maharashtra', 'Swarna Iyer', 91.0, 'Data Science', 'M.Tech Data Science'),
(21, 'adithya.singh@example.com', 1.0, 'Male', 'UG', 'Pune', 'Maharashtra', 'Adithya Singh', 78.5, 'Mechanical Engineering', 'B.Tech Mechanical'),
(26, 'meera.nair@example.com', 3.0, 'Female', 'PG', 'Kochi', 'Kerala', 'Meera Nair', 88.7, 'Business Administration', 'MBA');

